spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minibudget
    username: sa_minibudget
    password: sa_minibudget
    hikari.pool-name: ${spring.application.name}_pool
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog.master.xml
